rootProject.name = "kodilla-course2"
include("kodilla-testing")
include("kodilla-stream")
include("kodilla-exception")
include("kodilla-good-patterns")
include("kodilla-spring-intro")
include("kodilla-spring")
include("kodilla-spring-web")
include("kodilla-pattern")
include("kodilla-patterns")
include("kodilla-jdbc")
include("kodilla-sudoku")
include("kodilla-hibernate")
